/*****************************************************************************
 * VCLib                                                                     *
 * Visual Computing Library                                                  *
 *                                                                           *
 * Copyright(C) 2021-2025                                                    *
 * Visual Computing Lab                                                      *
 * ISTI - Italian National Research Council                                  *
 *                                                                           *
 * All rights reserved.                                                      *
 *                                                                           *
 * This program is free software; you can redistribute it and/or modify      *
 * it under the terms of the Mozilla Public License Version 2.0 as published *
 * by the Mozilla Foundation; either version 2 of the License, or            *
 * (at your option) any later version.                                       *
 *                                                                           *
 * This program is distributed in the hope that it will be useful,           *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of            *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the              *
 * Mozilla Public License Version 2.0                                        *
 * (https://www.mozilla.org/en-US/MPL/2.0/) for more details.                *
 ****************************************************************************/

#ifndef VCL_BGFX_DRAWABLE_LINES_GPU_GENERATED_LINES_H
#define VCL_BGFX_DRAWABLE_LINES_GPU_GENERATED_LINES_H

#include "line_settings.h"

#include <vclib/bgfx/buffers.h>
#include <vclib/bgfx/context.h>
#include <vclib/bgfx/drawable/lines_common/lines.h>

namespace vcl {

class GPUGeneratedLines : public Lines<LineSettings>
{
    bgfx::ProgramHandle mComputeVerticesPH =
        Context::instance()
            .programManager()
            .getComputeProgram<ComputeProgram::LINES>();

    bgfx::ProgramHandle mLinesPH =
        Context::instance()
            .programManager()
            .getProgram<VertFragProgram::LINES>();

    // buffer containing the input points - will be the input of the compute
    // shader
    VertexBuffer mPoints;

    // buffer of vertices generated by the compute shader, and used by the
    // vertex/fragment shaders
    VertexBuffer mVertices;

    // buffer of indices generated by the compute shader, and used by the
    // vertex/fragment shaders
    IndexBuffer mIndices;

public:
    GPUGeneratedLines() { checkCaps(); }

    GPUGeneratedLines(const std::vector<LinesVertex>& points);

    void swap(GPUGeneratedLines& other);

    void draw(uint viewId) const;

    void setPoints(const std::vector<LinesVertex>& points);

private:
    void checkCaps() const
    {
        const bgfx::Caps* caps = bgfx::getCaps();
        const bool computeSupported = bool(caps->supported & BGFX_CAPS_COMPUTE);
        if (!computeSupported) {
            throw std::runtime_error("GPU compute not supported");
        }
    }

    void allocateAndSetPointsBuffer(const std::vector<LinesVertex>& points);

    void allocateVertexBuffer(uint pointsSize);

    void allocateIndexBuffer(uint pointsSize);

    void generateVerticesAndIndicesBuffers(uint pointsSize);
};

} // namespace vcl

#endif // VCL_BGFX_DRAWABLE_LINES_GPU_GENERATED_LINES_H
