name: 'Build Python Wheel'
description: 'Set up Python, install build dependencies, and build a wheel'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
  os:
    description: 'The OS (Linux, Windows, macOS)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Python ${{ inputs.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
        
    - name: Build Wheel
      shell: bash
      run: |
        PY_VER_CLEAN=$(echo "${{ inputs.python-version }}" | tr -d '.')
        VENV_DIR="venv_${PY_VER_CLEAN}"
        
        python3 -m venv $VENV_DIR
        
        if [[ "${{ inputs.os }}" == "Windows" ]]; then
          source $VENV_DIR/Scripts/activate
        else
          source $VENV_DIR/bin/activate
        fi
        
        export VCLIB_USE_CCACHE=1
        python -m pip install --upgrade pip setuptools wheel build
        python -m build --wheel --no-isolation --outdir dist
        deactivate || true
