/*****************************************************************************
 * VCLib                                                                     *
 * Visual Computing Library                                                  *
 *                                                                           *
 * Copyright(C) 2021-2026                                                    *
 * Visual Computing Lab                                                      *
 * ISTI - Italian National Research Council                                  *
 *                                                                           *
 * All rights reserved.                                                      *
 *                                                                           *
 * This program is free software; you can redistribute it and/or modify      *
 * it under the terms of the Mozilla Public License Version 2.0 as published *
 * by the Mozilla Foundation; either version 2 of the License, or            *
 * (at your option) any later version.                                       *
 *                                                                           *
 * This program is distributed in the hope that it will be useful,           *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of            *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the              *
 * Mozilla Public License Version 2.0                                        *
 * (https://www.mozilla.org/en-US/MPL/2.0/) for more details.                *
 ****************************************************************************/

#ifndef VCL_VERSION_H
#define VCL_VERSION_H

/**
 * @defgroup version Version Information
 * @brief VCLib version information macros
 * 
 * @warning This file is automatically generated from version.h.in
 * Do not edit this file directly!
 * To update the version, use: python scripts/update_version.py <new_version>
 */

/**
 * @ingroup version
 * @brief Major version number
 */
#define VCLIB_VERSION_MAJOR 0

/**
 * @ingroup version
 * @brief Minor version number
 */
#define VCLIB_VERSION_MINOR 0

/**
 * @ingroup version
 * @brief Patch version number
 */
#define VCLIB_VERSION_PATCH 1

/**
 * @ingroup version
 * @brief Full version string
 */
#define VCLIB_VERSION_STRING "0.0.1"

/**
 * @ingroup version
 * @brief Version number as a single integer for comparison
 * Format: (major * 10000 + minor * 100 + patch)
 * Example: version 1.2.3 = 10203
 */
#define VCLIB_VERSION_NUMBER (VCLIB_VERSION_MAJOR * 10000 + VCLIB_VERSION_MINOR * 100 + VCLIB_VERSION_PATCH)

/**
 * @ingroup version
 * @brief Check if the library version is at least the specified version
 * @param major Major version to check
 * @param minor Minor version to check
 * @param patch Patch version to check
 */
#define VCLIB_VERSION_CHECK(major, minor, patch) \
    (VCLIB_VERSION_NUMBER >= ((major) * 10000 + (minor) * 100 + (patch)))

#endif // VCL_VERSION_H
