// VCLib - Visual Computing Library
// Copyright (C) 2021-2026 Visual Computing Lab, ISTI - CNR.
//
// This Source Code Form is subject to the terms of the Mozilla Public License,
// v. 2.0. If a copy of the MPL was not distributed with this file, You can
// obtain one at https://mozilla.org/MPL/2.0/.

#ifndef VCL_VERSION_H
#define VCL_VERSION_H

/**
 * @defgroup version Version Information
 * @brief VCLib version information macros
 *
 * @warning This file is automatically generated from version.h.in
 * Do not edit this file directly!
 * To update the version, use: python scripts/update_version.py <new_version>
 */

/**
 * @ingroup version
 * @brief Major version number
 */
#define VCLIB_VERSION_MAJOR 0

/**
 * @ingroup version
 * @brief Minor version number
 */
#define VCLIB_VERSION_MINOR 0

/**
 * @ingroup version
 * @brief Patch version number
 */
#define VCLIB_VERSION_PATCH 1

/**
 * @ingroup version
 * @brief Full version string
 */
#define VCLIB_VERSION_STRING "0.0.1"

/**
 * @ingroup version
 * @brief Version number as a single integer for comparison
 * Format: (major * 10000 + minor * 100 + patch)
 * Example: version 1.2.3 = 10203
 */
#define VCLIB_VERSION_NUMBER                                   \
    (VCLIB_VERSION_MAJOR * 10000 + VCLIB_VERSION_MINOR * 100 + \
     VCLIB_VERSION_PATCH)

/**
 * @ingroup version
 * @brief Check if the library version is at least the specified version
 * @param major Major version to check
 * @param minor Minor version to check
 * @param patch Patch version to check
 */
#define VCLIB_VERSION_CHECK(major, minor, patch) \
    (VCLIB_VERSION_NUMBER >= ((major) * 10000 + (minor) * 100 + (patch)))

#endif // VCL_VERSION_H
