name: 'Build and Install bgfx'
description: 'Set up and compile bgfx once so it can be reused across different wheel builds.'

inputs:
  bgfx-version:
    description: 'The tag or branch of bgfx.cmake to clone'
    required: false
    default: 'v1.159.9485-575'

runs:
  using: 'composite'
  steps:
    - name: Build and Install bgfx
      uses: alemuntoni/install-bgfx-cmake@v1
      with:
        bgfx-version: ${{ inputs.bgfx-version }}
