name: 'Build and Install bgfx'
description: 'Set up and compile bgfx once so it can be reused across different wheel builds.'

inputs:
  bgfx-version:
    description: 'The tag or branch of bgfx.cmake to clone'
    required: false
    default: 'v1.147.9336-554'

runs:
  using: 'composite'
  steps:
    - name: Clone bgfx
      shell: bash
      run: |
        git clone --recursive https://github.com/bkaradzic/bgfx.cmake.git -b ${{ inputs.bgfx-version }} bgfx-build

    - name: Configure and Build bgfx
      shell: bash
      env:
        WORKSPACE: ${{ github.workspace }}
      run: |
        cd bgfx-build
        export CMAKE_C_COMPILER_LAUNCHER=ccache
        export CMAKE_CXX_COMPILER_LAUNCHER=ccache
        
        WORKSPACE_PATH="${WORKSPACE//\\//}"
        
        # We build statically, as python wheels include the static library.
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DBGFX_BUILD_EXAMPLES=OFF -DBUILD_SHARED_LIBS=OFF -DBGFX_WITH_WAYLAND=OFF -DCMAKE_INSTALL_PREFIX="$WORKSPACE_PATH/bgfx-install"
        cmake --build build --config Release --target install
        
        echo "CMAKE_PREFIX_PATH=$WORKSPACE_PATH/bgfx-install" >> $GITHUB_ENV
