name: Reusable Build VCLib Packages

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        description: "The commit SHA or ref to checkout. Defaults to the workflow trigger ref."

jobs:
  build_vclib_packages:
    name: Build VCLib Package (${{ matrix.os }}, ${{ matrix.package_type }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'ubuntu-24.04-arm', 'macos-15-intel', 'macos-latest', 'windows-2022']
        package_type: ['core', 'all']
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive
        ref: ${{ inputs.ref }}

    - name: Setup MSVC
      uses: TheMrMilchmann/setup-msvc-dev@v4
      if: runner.os == 'Windows'
      with:
        arch: x64

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        cache: 'true'
        version: '6.10.*'

    - name: Install dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install cmake ninja-build libtbb-dev
        sudo apt-get install libembree-dev
        sudo apt-get install freeglut3-dev libgl1-mesa-dev libxi-dev libxinerama-dev libxcursor-dev libxrandr-dev libgmp-dev libmpfr-dev

    - name: Install dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install cmake ninja
        brew install embree gmp mpfr

    - name: Install dependencies
      if: runner.os == 'Windows'
      shell: bash
      run: |
        choco install -y cmake ninja

    - name: Ccache
      uses: hendrikmuhs/ccache-action@v1.2.23
      with:
        key: package-${{ matrix.os }}-${{ matrix.package_type }}-${{ github.ref_name }}

    - name: Build and Install VCLib
      shell: bash
      run: |
        PRESET="vclib-${{ matrix.package_type }}-install"
        cmake -S . -B build-vclib --preset=$PRESET \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        cmake --build build-vclib
        cmake --install build-vclib --prefix "${{ github.workspace }}/install-vclib"

    - name: Upload VCLib Package
      uses: actions/upload-artifact@v7
      with:
        name: vclib-package-${{ matrix.package_type }}-${{ runner.os }}-${{ runner.arch }}
        path: install-vclib
        include-hidden-files: true
