name: Reusable Build Docs

on:
  workflow_call:

jobs:
  build_docs:
    name: Build Docs
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7
      - name: Install dependencies
        run: | 
          sudo apt-get install doxygen graphviz
      - name: Build Docs
        run: |
          python3 scripts/generate_versioned_docs.py --verbose
      - name: Upload Docs
        uses: actions/upload-artifact@v7
        with:
          name: vclib_docs
          path: docs/_doxygen/html
