name: Build Docs

on:
  workflow_dispatch

jobs:
  build_docs:
    uses: ./.github/workflows/_build_docs.yml

  upload_docs:
    needs: build_docs
    name: Upload Docs
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7
        with:
          repository: alemuntoni/alemuntoni.github.io
          token: ${{ secrets.PAT }}
      - name: Delete old docs
        run: |
          cd static/vclib
          rm -R *
      - name: Download new docs
        uses: actions/download-artifact@v8
        with:
          name: vclib_docs
          path: static/vclib/
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Automatic Update VCLib docs
          commit_user_name: alemuntoni
          commit_user_email: ${{ secrets.EMAIL }}
          commit_author: alemuntoni <${{ secrets.EMAIL }}>
