name: Standalone Examples - FindPackage

on:
  workflow_dispatch:

jobs:
  StandaloneExamples-FindPackage:
    uses: ./.github/workflows/_standalone_examples_template.yml
    with:
      integration_mode: 'find_package'
