name: Standalone Examples - FetchContent

on:
  workflow_dispatch:

jobs:
  run-fetchcontent:
    uses: ./.github/workflows/_standalone_examples_template.yml
    with:
      integration_mode: 'FetchContent'
